# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ads_mem_examples.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dprotos/ads_mem_examples.proto\"\x98\x06\n\x0e\x41\x64sMemExamples\x12\x15\n\x05\x64\x65\x62ug\x18\xe7\x07 \x01(\x08:\x05\x66\x61lse\x12\x17\n\nbatch_size\x18\x01 \x01(\x05:\x03\x31\x32\x38\x12 \n\x12\x66\x65\x61ture_dimensions\x18\x02 \x01(\x05:\x04\x31\x35\x33\x36\x12\x1e\n\x13max_stmts_per_image\x18\x03 \x01(\x05:\x01\x33\x12\x18\n\x0cmax_stmt_len\x18\x04 \x01(\x05:\x02\x32\x30\x12\x1d\n\x11number_of_regions\x18\x05 \x01(\x05:\x02\x31\x30\x12%\n\x16number_of_val_examples\x18\x06 \x01(\x05:\x05\x31\x30\x30\x30\x30\x12)\n\x1dnumber_of_val_stmts_per_image\x18\x07 \x01(\x05:\x02\x31\x35\x12\x1a\n\x12image_feature_path\x18\n \x01(\t\x12\x1b\n\x13region_feature_path\x18\x0b \x01(\t\x12\x1c\n\x14statement_vocab_path\x18\x0f \x01(\t\x12\x1c\n\x14statement_annot_path\x18\x10 \x01(\t\x12\x1b\n\x13\x64\x65nsecap_vocab_path\x18\x11 \x01(\t\x12\x1b\n\x13\x64\x65nsecap_annot_path\x18\x12 \x01(\t\x12\x19\n\x11symbol_annot_path\x18\x13 \x01(\t\x12\x1b\n\x13symbol_cluster_path\x18\x14 \x01(\t\x12!\n\x13shuffle_buffer_size\x18\x19 \x01(\x05:\x04\x31\x30\x30\x30\x12\x46\n\x12\x64\x61ta_provider_mode\x18\x1a \x01(\x0e\x32 .AdsMemExamples.DataProviderMode:\x08\x46ROM_CPU\x12#\n\x17max_densecaps_per_image\x18\x1e \x01(\x05:\x02\x31\x30\x12\x1c\n\x10max_densecap_len\x18\x1f \x01(\x05:\x02\x31\x30\x12\"\n\x13use_single_densecap\x18  \x01(\x08:\x05\x66\x61lse\x12 \n\x15max_symbols_per_image\x18! \x01(\x05:\x01\x35\".\n\x10\x44\x61taProviderMode\x12\x0c\n\x08\x46ROM_CPU\x10\x01\x12\x0c\n\x08\x46ROM_GPU\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.ads_mem_examples_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADSMEMEXAMPLES._serialized_start=34
  _ADSMEMEXAMPLES._serialized_end=826
  _ADSMEMEXAMPLES_DATAPROVIDERMODE._serialized_start=780
  _ADSMEMEXAMPLES_DATAPROVIDERMODE._serialized_end=826
# @@protoc_insertion_point(module_scope)
