# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/advise_model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import utils_pb2 as protos_dot_utils__pb2
from protos import text_encoders_pb2 as protos_dot_text__encoders__pb2
from protos import triplet_mining_pb2 as protos_dot_triplet__mining__pb2
from protos import mlp_pb2 as protos_dot_mlp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protos/advise_model.proto\x1a\x12protos/utils.proto\x1a\x1aprotos/text_encoders.proto\x1a\x1bprotos/triplet_mining.proto\x1a\x10protos/mlp.proto\"\xcc\x07\n\x0b\x41\x44VISEModel\x12#\n\x15use_image_as_proposal\x18\x01 \x01(\x08:\x04true\x12!\n\rimage_encoder\x18\x02 \x01(\x0b\x32\n.FCEncoder\x12!\n\rimage_decoder\x18\x03 \x01(\x0b\x32\n.FCEncoder\x12\"\n\x0cstmt_encoder\x18\x04 \x01(\x0b\x32\x0c.TextEncoder\x12<\n\x0epooling_method\x18\x05 \x01(\x0e\x32\x1a.ADVISEModel.PoolingMethod:\x08\x41VG_POOL\x12-\n\x19image_attention_predictor\x18\x06 \x01(\x0b\x32\n.FCEncoder\x12&\n\x1bjoint_emb_dropout_keep_prob\x18\x10 \x01(\x02:\x01\x31\x12&\n\x0etriplet_mining\x18\x11 \x01(\x0b\x32\x0e.TripletMining\x12\x1b\n\x0etriplet_margin\x18\x12 \x01(\x02:\x03\x30.1\x12\"\n\x17\x61utoencoder_loss_weight\x18\x13 \x01(\x02:\x01\x31\x12\x1f\n\x14log_prob_loss_weight\x18\x14 \x01(\x02:\x01\x30\x12&\n\x17use_adversarial_dropout\x18\x15 \x01(\x08:\x05\x66\x61lse\x12\x1f\n\x14\x64\x65nsecap_loss_weight\x18\x1e \x01(\x02:\x01\x30\x12&\n\x10\x64\x65nsecap_encoder\x18\x1f \x01(\x0b\x32\x0c.TextEncoder\x12\x1d\n\x12symbol_loss_weight\x18  \x01(\x02:\x01\x30\x12$\n\x0esymbol_encoder\x18! \x01(\x0b\x32\x0c.TextEncoder\x12#\n\x14use_knowledge_branch\x18\" \x01(\x08:\x05\x66\x61lse\x12$\n\x11symbol_classifier\x18# \x01(\x0b\x32\t.MLPModel\x12V\n\x17knowledge_training_mode\x18$ \x01(\x0e\x32\".ADVISEModel.KnowledgeTrainingMode:\x11RESIDUAL_TRAINING\x12\x1b\n\x13symbol_cluster_path\x18% \x01(\t\"U\n\rPoolingMethod\x12\x0c\n\x08\x41VG_POOL\x10\x01\x12\x0c\n\x08\x41TT_POOL\x10\x02\x12\x13\n\x0f\x41TT_POOL_DS_SUM\x10\x03\x12\x13\n\x0f\x41TT_POOL_DS_MAX\x10\x04\"B\n\x15KnowledgeTrainingMode\x12\x12\n\x0eJOINT_TRAINING\x10\x01\x12\x15\n\x11RESIDUAL_TRAINING\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.advise_model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADVISEMODEL._serialized_start=125
  _ADVISEMODEL._serialized_end=1097
  _ADVISEMODEL_POOLINGMETHOD._serialized_start=944
  _ADVISEMODEL_POOLINGMETHOD._serialized_end=1029
  _ADVISEMODEL_KNOWLEDGETRAININGMODE._serialized_start=1031
  _ADVISEMODEL_KNOWLEDGETRAININGMODE._serialized_end=1097
# @@protoc_insertion_point(module_scope)
