# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/mlp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from object_detection.protos import hyperparams_pb2 as object__detection_dot_protos_dot_hyperparams__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/mlp.proto\x1a)object_detection/protos/hyperparams.proto\"\xfb\x02\n\x08MLPModel\x12\x12\n\x05scope\x18\x01 \x01(\t:\x03mlp\x12\"\n\x17input_dropout_keep_prob\x18\x02 \x01(\x02:\x01\x31\x12@\n\x12hidden_hyperparams\x18\x03 \x01(\x0b\x32$.object_detection.protos.Hyperparams\x12\x18\n\rhidden_layers\x18\x04 \x01(\x05:\x01\x30\x12\x19\n\x0chidden_units\x18\x05 \x01(\x05:\x03\x32\x35\x36\x12#\n\x18hidden_dropout_keep_prob\x18\x06 \x01(\x02:\x01\x31\x12@\n\x12output_hyperparams\x18\x07 \x01(\x0b\x32$.object_detection.protos.Hyperparams\x12\x19\n\x0coutput_units\x18\x08 \x01(\x05:\x03\x32\x35\x36\x12#\n\x18output_dropout_keep_prob\x18\t \x01(\x02:\x01\x31\x12\x19\n\x0f\x63heckpoint_path\x18\n \x01(\t:\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.mlp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MLPMODEL._serialized_start=64
  _MLPMODEL._serialized_end=443
# @@protoc_insertion_point(module_scope)
