# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import vse_model_pb2 as protos_dot_vse__model__pb2
from protos import advise_model_pb2 as protos_dot_advise__model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/model.proto\x1a\x16protos/vse_model.proto\x1a\x19protos/advise_model.proto\"V\n\x05Model\x12\x1e\n\tvse_model\x18\x01 \x01(\x0b\x32\t.VSEModelH\x00\x12$\n\x0c\x61\x64vise_model\x18\x02 \x01(\x0b\x32\x0c.ADVISEModelH\x00\x42\x07\n\x05model')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODEL._serialized_start=73
  _MODEL._serialized_end=159
# @@protoc_insertion_point(module_scope)
