# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/pipeline.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import ads_mem_examples_pb2 as protos_dot_ads__mem__examples__pb2
from protos import model_pb2 as protos_dot_model__pb2
from protos import train_config_pb2 as protos_dot_train__config__pb2
from protos import eval_config_pb2 as protos_dot_eval__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/pipeline.proto\x1a\x1dprotos/ads_mem_examples.proto\x1a\x12protos/model.proto\x1a\x19protos/train_config.proto\x1a\x18protos/eval_config.proto\"\x90\x01\n\x08Pipeline\x12\'\n\x0e\x65xample_reader\x18\x01 \x01(\x0b\x32\x0f.AdsMemExamples\x12\x15\n\x05model\x18\x02 \x01(\x0b\x32\x06.Model\x12\"\n\x0ctrain_config\x18\x03 \x01(\x0b\x32\x0c.TrainConfig\x12 \n\x0b\x65val_config\x18\x04 \x01(\x0b\x32\x0b.EvalConfig')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.pipeline_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PIPELINE._serialized_start=130
  _PIPELINE._serialized_end=274
# @@protoc_insertion_point(module_scope)
