# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/triplet_mining.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprotos/triplet_mining.proto\"\xac\x01\n\rTripletMining\x12\x1c\n\x08mine_all\x18\x01 \x01(\x0b\x32\x08.MineAllH\x00\x12\x1e\n\tmine_hard\x18\x02 \x01(\x0b\x32\t.MineHardH\x00\x12\'\n\x0emine_semi_hard\x18\x03 \x01(\x0b\x32\r.MineSemiHardH\x00\x12\"\n\x0bmine_random\x18\x04 \x01(\x0b\x32\x0b.MineRandomH\x00\x42\x10\n\x0etriplet_mining\"\t\n\x07MineAll\"\x0e\n\x0cMineSemiHard\"\x1c\n\x08MineHard\x12\x10\n\x05top_k\x18\x01 \x01(\x05:\x01\x31\"-\n\nMineRandom\x12\x1f\n\x14negatives_per_anchor\x18\x01 \x01(\x05:\x01\x31')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.triplet_mining_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRIPLETMINING._serialized_start=32
  _TRIPLETMINING._serialized_end=204
  _MINEALL._serialized_start=206
  _MINEALL._serialized_end=215
  _MINESEMIHARD._serialized_start=217
  _MINESEMIHARD._serialized_end=231
  _MINEHARD._serialized_start=233
  _MINEHARD._serialized_end=261
  _MINERANDOM._serialized_start=263
  _MINERANDOM._serialized_end=308
# @@protoc_insertion_point(module_scope)
