# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/utils.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from object_detection.protos import hyperparams_pb2 as object__detection_dot_protos_dot_hyperparams__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/utils.proto\x1a)object_detection/protos/hyperparams.proto\"\xc7\x01\n\tFCEncoder\x12\x19\n\x05scope\x18\x01 \x01(\t:\nfc_encoder\x12\x18\n\x0bnum_outputs\x18\x02 \x01(\x05:\x03\x32\x30\x30\x12\"\n\x17input_dropout_keep_prob\x18\x03 \x01(\x02:\x01\x31\x12#\n\x18output_dropout_keep_prob\x18\x04 \x01(\x02:\x01\x31\x12<\n\x0e\x66\x63_hyperparams\x18\x05 \x01(\x0b\x32$.object_detection.protos.Hyperparams')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.utils_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FCENCODER._serialized_start=66
  _FCENCODER._serialized_end=265
# @@protoc_insertion_point(module_scope)
