# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/vse_model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import utils_pb2 as protos_dot_utils__pb2
from protos import text_encoders_pb2 as protos_dot_text__encoders__pb2
from protos import triplet_mining_pb2 as protos_dot_triplet__mining__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/vse_model.proto\x1a\x12protos/utils.proto\x1a\x1aprotos/text_encoders.proto\x1a\x1bprotos/triplet_mining.proto\"\xbe\x01\n\x08VSEModel\x12!\n\rimage_encoder\x18\x01 \x01(\x0b\x32\n.FCEncoder\x12\"\n\x0cstmt_encoder\x18\x02 \x01(\x0b\x32\x0c.TextEncoder\x12&\n\x1bjoint_emb_dropout_keep_prob\x18\n \x01(\x02:\x01\x31\x12&\n\x0etriplet_mining\x18\x0b \x01(\x0b\x32\x0e.TripletMining\x12\x1b\n\x0etriplet_margin\x18\x0c \x01(\x02:\x03\x30.2')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.vse_model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VSEMODEL._serialized_start=104
  _VSEMODEL._serialized_end=294
# @@protoc_insertion_point(module_scope)
